config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :games
  resources :moves, only: [:create]
  resources :users, only: [:index, :show]
  root "games#index"
end

app/models/game.rb
class Game < ActiveRecord::Base
  # validates :diff, inclusion: { in: %w(1 2 3 4 5), message: "1-5" }
  belongs_to :user, class_name: 'User', foreign_key: 'user_id'
  belongs_to :opponent, class_name: 'User', foreign_key: 'opponent_id'
  has_many :moves

  def whosmove
    Move.last.try(:value)
  end

  def winner
    win=3
    maxindicatorx=0
    maxindicator0=0
    message = ""
    winning_combinations = [[0,1,2], [3,4,5], [6,7,8], [0,3,6], [1,4,7], [2,5,8], [0,4,8], [2,4,6]]
    testx = [" "," "," "," "," "," "," "," "," "]
    i=0
    while i<9
      if (moves.find_by_number(i).present?)
        testx[i] = moves.find_by_number(i).number
      end
      i+=1
    end
    #test for matches to winning combinations
    j=0
    k=0
    while j<8
      indicatorx = 0
      indicator0 = 0
      while k<3
        if testx.include?(winning_combinations[j][k]) && result = moves.find_by_number(j).try(:value) == 'x'
          indicatorx=indicatorx+1
        elsif testx.include?(winning_combinations[j][k]) && result = moves.find_by_number(j).try(:value) == 'o'
          indicator0=indicator0+1
        end
        k+=1
      end
      if(indicatorx>maxindicatorx)
        maxindicatorx = indicatorx
      end
      if(indicator0>maxindicator0)
        maxindicator0 = indicator0
      end
      j+=1
    end
    maxindicatorx
  end


  # First move is always x
  def next_value
    return "x" if first_move?
    last_move == "x" ? "o" : "x" 
  end

  private

  def first_move?
    moves.empty?
  end

  def last_move
    moves.last.value
  end
end

app/models/move.rb
class Move < ActiveRecord::Base
  # validates :value, inclusion: { in: %w(0 X), message: "Xor0 Xor0 Xor0 !!!!!"}
  validates :number, inclusion: { in: (0...9).to_a}
  # validates :number, uniqueness: true
  belongs_to :game
  belongs_to :user
 

  # def moves_in_game
  #   game.moves.find_by_number(number).present?
  # end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  # validates :name, uniqueness: true
  has_many :games_1, class_name: 'Game', foreign_key: 'user_id'
  has_many :games_2, class_name: 'Game', foreign_key: 'opponent_id'
  has_many :moves, through: :games

  def all_games
    games_1 + games_2
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:show, :edit, :update, :destroy]

  # GET /games
  # GET /games.json
  def index
    @games = Game.all
  end

  # GET /games/1
  # GET /games/1.json
  def show
    @game.whosmove
  end

  # GET /games/new
  def new
    @game = Game.new
  end

  # GET /games/1/edit
  def edit
  end

  # POST /games
  # POST /games.json
  def create
    @game = Game.new(game_params)

    respond_to do |format|
      if @game.save
        format.html { redirect_to @game, notice: 'Game was successfully created.' }
        format.json { render :show, status: :created, location: @game }
      else
        format.html { render :new }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /games/1
  # PATCH/PUT /games/1.json
  def update
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to @game, notice: 'Game was successfully updated.' }
        format.json { render :show, status: :ok, location: @game }
      else
        format.html { render :edit }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game.destroy
    respond_to do |format|
      format.html { redirect_to games_url, notice: 'Game was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def game_params
      params.require(:game).permit(:user_id, :opponent_id, :diff, :result)
    end
end

app/controllers/moves_controller.rb
class MovesController < ApplicationController

  def create
    @game = Game.find(params[:game_id])
    @move = @game.moves.new(user_id: params[:user_id], number: params[:number], value: params[:value])
    if @move.save
      redirect_to @game
    else
      redirect_to @game, notice: 'There was a problem.'  
    end
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/moves_helper.rb
module MovesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/games/_form.html.erb
<%= form_for(@game) do |f| %>
<% if @game.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@game.errors.count, "error") %> prohibited this game from being saved:</h2>

  <ul>
    <% @game.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="field">
  <%= f.label :opponent_id, 'Who would you like to play?' %><br>
  <%= hidden_field_tag 'game[user_id]', current_user.id %>
  <%= f.collection_select :opponent_id, User.all, :id, :email %>
</div>
<div class="actions">
  <%= f.submit 'Start' %>
</div>

<% end %>

app/views/games/edit.html.erb
<h1>Editing Game</h1>

<%= render 'form' %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>

app/views/games/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Games</h1>
<P>"CURRENT USER" 
<%  current_user  %>
</P>
<table>

<%= link_to 'New Game', new_game_path %>

  <thead>
    <tr>
      <th>User</th>
      <th>Opponent</th>
      <th>Diff</th>
      <th>Result</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @games.each do |game| %>
      <tr>
        <td><%= game.user_id %></td>
        <td><%= game.opponent_id %></td>
        <td><%= game.diff %></td>
        <td><%= game.result %></td>
        <td><%= link_to 'Show', game %></td>
        <td><%= link_to 'Edit', edit_game_path(game) %></td>
        <td><%= link_to 'Destroy', game, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/games/new.html.erb
<h1>New Game</h1>

<%= render 'form' %>

<%= link_to 'Back', games_path %>

app/views/games/show.html.erb
<p id="notice"><%= notice %></p>

<table>
  <% (0..8).to_a.each_slice(3) do |slice| %>
    <tr>
      <% slice.each do |cell| %>
        <td class="nccell">
          <% if @game.moves.find_by_number(cell) %>
            <%= @game.moves.find_by_number(cell).value %>
          <% else %>
            <%= button_to "  ", moves_path(game_id: @game.id, number: cell, user_id: current_user.id, value: @game.next_value), method: :post %>
          <% end %>
        </td>
      <% end %>
    </tr>
  <% end %>
</table>

<p>User: <%= @game.user.email %></p>
<p>Opp: <%= @game.opponent.email %></p>
<p>Num: <%= @game.winner %></p>


<%= link_to 'Edit', edit_game_path(@game) %>
<%= link_to 'Back', games_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />

  <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>

  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "vendor/modernizr" %>
  <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body>
  <div class="icon-bar five-up">
    <a class="home" href="/">
      <%= image_tag('fi-home.svg') %>
      <label>Home</label>
    </a>
    <% if user_signed_in? %>
    <a class="Games" href="/games">
      <%= image_tag('noughts1.jpg') %>
      <label>Games</label>
    </a>
    <%= link_to image_tag('Logout.png'), destroy_user_session_path, method: :delete %> >
    <%= link_to image_tag('Edit.png'), edit_user_registration_path %> 
    <% else %>
    <%= link_to image_tag("LoginIcon.jpg"), new_user_session_path %>
    <%= link_to image_tag('register.png'), new_user_registration_path %>
    <% end %>
  </div>
  <%= yield %>

  <!-- <div> -->
  <!-- <nav> -->
  <!-- <ul> -->
  <!-- <li><a href="/">Home</a></li> -->
  <!-- <li><a href="/games">Play Game</a></li> -->
  <!-- <li><a href="/users">All Users</a></li> -->
  <!-- </ul> -->
  <!-- <ul> -->
  <!-- <% if user_signed_in? %> -->
  <!-- <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li> -->
  <!-- <li><%= link_to "Edit Profile", edit_user_registration_path %></li> -->
  <!-- <% else %> -->
  <!-- <li><%= link_to "Login", new_user_session_path %></li> -->
  <!-- <li><%= link_to "Create an account", new_user_registration_path %></li> -->
  <!-- <% end %> -->
  <!-- </ul> -->
  <!-- </nav> -->
  <!-- </div> -->



</body>
</html>

app/views/moves/_form.html.erb
<%= form_for(@move) do |f| %>
  <% if @move.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@move.errors.count, "error") %> prohibited this move from being saved:</h2>

      <ul>
      <% @move.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :game_id %><br>
    <%= f.text_field :game_id %>
  </div>
  <div class="field">
    <%= f.label :number %><br>
    <%= f.number_field :number %>
  </div>
  <div class="field">
    <%= f.label :value %><br>
    <%= f.text_field :value %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/moves/edit.html.erb
<h1>Editing Move</h1>

<%= render 'form' %>

<%= link_to 'Show', @move %> |
<%= link_to 'Back', moves_path %>

app/views/moves/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Moves</h1>

<table>
  <thead>
    <tr>
      <th>Game</th>
      <th>Number</th>
      <th>Value</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @moves.each do |move| %>
      <tr>
        <td><%= move.game_id %></td>
        <td><%= move.number %></td>
        <td><%= move.value %></td>
        <td><%= move.user_id %></td>
        <td><%= link_to 'Show', move %></td>
        <td><%= link_to 'Edit', edit_move_path(move) %></td>
        <td><%= link_to 'Destroy', move, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Move', new_move_path %>

app/views/moves/new.html.erb
<h1>New Move</h1>

<%= render 'form' %>

<%= link_to 'Back', moves_path %>

app/views/moves/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Game:</strong>
  <%= @move.game_id %>
</p>

<p>
  <strong>Number:</strong>
  <%= @move.number %>
</p>

<p>
  <strong>Value:</strong>
  <%= @move.value %>
</p>

<p>
  <strong>User:</strong>
  <%= @move.user_id %>
</p>

<%= link_to 'Edit', edit_move_path(@move) %> |
<%= link_to 'Back', moves_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<%= link_to 'Back', users_path %>